// Services
export {
  createCampaign,
  getCampaign,
  listCampaigns,
  startCampaign,
  pauseCampaign,
  stopCampaign,
  updateStats,
  checkStopConditions,
  getNextContacts,
  analyzeCampaignPerformance,
} from './services/campaign-service';
export {
  analyzeCall,
  analyzeCallWithAI,
  calculateSentiment,
  calculateSentimentWithAI,
  extractKeyInfo,
  checkCompliance,
  generateSummary,
  calculateTalkRatio,
} from './services/conversational-intel';
export {
  getInboundConfig,
  saveInboundConfig,
  detectCallerIntent,
  handleInboundCall,
  screenCaller,
  routeCall,
  isAfterHours,
  collectIntakeForm,
} from './services/inbound-agent';
export {
  provisionNumber,
  releaseNumber,
  getNumber,
  listNumbers,
  assignPersona,
  assignInboundConfig,
} from './services/number-manager';
export {
  initiateOutboundCall,
  detectVoicemail,
  dropVoicemail,
  checkGuardrails,
  initiateOutboundCallForCampaign,
} from './services/outbound-agent';
export {
  createPersona,
  getPersona,
  listPersonas,
  updatePersona,
  addConsentEntry,
  revokeConsent,
  validateConsentChain,
  generateWatermarkId,
  suggestPersonaTraits,
} from './services/persona-service';
export {
  createScript,
  getScript,
  listScripts,
  updateScript,
  startExecution,
  advanceNode,
  evaluateBranch,
  validateScript,
  generateScriptWithAI,
  optimizeScript,
} from './services/script-engine';

// Types
export type {
  VoiceProvider,
  ProvisionedNumber,
  OutboundCallConfig,
  CallSession,
  CallStatus,
  ConsentCheck,
  OutboundCallRequest,
  CallGuardrails,
  OutboundCallResult,
  GuardrailCheckResult,
  InboundConfig,
  RoutingRule,
  AfterHoursConfig,
  InboundCallResult,
  CallScript,
  ScriptNode,
  ScriptBranch,
  ScriptExecution,
  VoicePersona,
  VoiceConfig,
  PersonalityConfig,
  ConsentChainEntry,
  TranscriptSegment,
  CallAnalysis,
  ExtractedInfo,
  ComplianceIssue,
  CallSummary,
  Campaign,
  CampaignSchedule,
  StopCondition,
  CampaignStats,
  ManagedNumber,
} from './types';
