import type { ImpersonationSafeguard } from './types';

// In-memory consent store (placeholder for database-backed storage)
const consentStore = new Map<string, { voiceCloneId: string; consentTimestamp: Date }>();
const watermarkStore = new Set<string>();

export async function verifyVoiceCloneConsent(
  userId: string,
  voiceCloneId: string
): Promise<ImpersonationSafeguard> {
  const key = `${userId}:${voiceCloneId}`;
  const consent = consentStore.get(key);

  return {
    consentVerified: !!consent,
    watermarkApplied: watermarkStore.has(voiceCloneId),
    disclosureIncluded: false,
    voiceCloneId,
    consentTimestamp: consent?.consentTimestamp,
  };
}

export async function applyWatermark(audioContentId: string): Promise<ImpersonationSafeguard> {
  watermarkStore.add(audioContentId);

  return {
    consentVerified: true,
    watermarkApplied: true,
    disclosureIncluded: true,
    voiceCloneId: audioContentId,
  };
}

export function generateDisclosure(context: string): string {
  const disclosures: Record<string, string> = {
    voice_call: 'This call is being handled by an AI assistant on behalf of the user. The voice you hear is AI-generated.',
    email: 'This message was drafted by an AI assistant and sent on behalf of the user.',
    chat: 'You are communicating with an AI assistant acting on behalf of the user.',
    voicemail: 'This voicemail was generated by an AI assistant on behalf of the user.',
  };

  return disclosures[context] ??
    `This communication was generated by an AI assistant. Content may be AI-generated and should be verified.`;
}

// Helper to record consent (used by API routes)
export function recordConsent(userId: string, voiceCloneId: string): void {
  const key = `${userId}:${voiceCloneId}`;
  consentStore.set(key, { voiceCloneId, consentTimestamp: new Date() });
}
